[package]
name = "ormdb-proto"
version.workspace = true
edition.workspace = true

[dependencies]
rkyv.workspace = true
bytes.workspace = true
thiserror.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
